### ISSUE TITLE
Abschlusspräsentation Planen

### ISSUE THREAD

**Issue by StephanM87** [StephanM87/Pr-sentationDataStewards#5]

**Comment by StephanM87** [comment]
Wie soll ich die Präsentation Planen, welche Plattform soll ich benutzen

**Comment by StephanM87** [comment]
Du kannst die Präsentation in Prezi oder Powerpojnt machen

**Comment by michaelosthege** [comment]
Für wen ist der Vortrag?

**Comment by StephanM87** [comment]
Für die Data Stewards der Rwth. Es gab einen einen Workshop zum Thema FAIR data management (vor etwa 2 Monaten) . Unter anderem kam dabei das Thema Projektmanagement zur Sprache, daraufhin hatte ich gitlab und Github als hervorragende Beispiele genannt. Jetzt stelle ich das Morgen mal als Projektmanagement Plattform auch für nicht SE vor :)
